""".

Revision ID: 147c1062dfb8
Revises: 308ed7aa8984
Create Date: 2025-04-25 08:58:24.381975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147c1062dfb8'
down_revision = '308ed7aa8984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
