"""empty message

Revision ID: 2cdfc4f8a7bc
Revises: e6e3e0973908
Create Date: 2025-04-29 13:33:19.583137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdfc4f8a7bc'
down_revision = 'e6e3e0973908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pallet_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('pallet_number')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
