"""empty message

Revision ID: 308ed7aa8984
Revises: 5c54ee5b0af2
Create Date: 2025-04-22 09:30:14.442285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '308ed7aa8984'
down_revision = '5c54ee5b0af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
