"""Add width and length back to rack model since copilot was so nice to remove it.

Revision ID: 5c54ee5b0af2
Revises: ca51d3b2338e
Create Date: 2025-04-18 14:53:47.095640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54ee5b0af2'
down_revision = 'ca51d3b2338e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Float()))
        batch_op.add_column(sa.Column('length', sa.Float()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('length')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
