"""Add shelf_spots to Pallet

Revision ID: 6a553d8d2b32
Revises: 2cdfc4f8a7bc
Create Date: 2025-05-21 15:50:59.393451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a553d8d2b32'
down_revision = '2cdfc4f8a7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_spots', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.drop_column('shelf_spots')

    # ### end Alembic commands ###
