"""add slot_index to pallets

Revision ID: 71d0ad66ea70
Revises: 50e96011944a
Create Date: 2025-06-09 14:56:48.763545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d0ad66ea70'
down_revision = '50e96011944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.drop_column('slot_index')

    # ### end Alembic commands ###
