"""empty message

Revision ID: 81d4c36e5215
Revises: c0a20d6a2c64
Create Date: 2025-04-18 11:59:54.885471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d4c36e5215'
down_revision = 'c0a20d6a2c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
