"""Add company_id to vaults

Revision ID: 8a43d4e1dcb1
Revises: 6a553d8d2b32
Create Date: 2025-06-04 09:20:34.815131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a43d4e1dcb1'
down_revision = '6a553d8d2b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vaults_company_id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vaults_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
