"""Add customer_id column to pallets

Revision ID: 9a583b97b6bc
Revises: 71d0ad66ea70
Create Date: 2025-06-13 13:05:31.468605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a583b97b6bc'
down_revision = '71d0ad66ea70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_pallets_customer_id",
            'customers',
            ['customer_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallets', schema=None) as batch_op:
        batch_op.drop_constraint("fk_pallets_customer_id", type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
