"""empty message

Revision ID: b36883bf1be2
Revises: e1841931a33a
Create Date: 2025-04-15 13:24:43.063445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36883bf1be2'
down_revision = 'e1841931a33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('width')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
