"""Add warehouse_id to Vault model

Revision ID: b3bb6d961e3f
Revises: 6c5e3cc4fc06
Create Date: 2025-04-16 15:54:37.555458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bb6d961e3f'
down_revision = '6c5e3cc4fc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
