"""empty message

Revision ID: c0a20d6a2c64
Revises: b3bb6d961e3f
Create Date: 2025-04-17 08:41:37.944702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # Add this import

# revision identifiers, used by Alembic.
revision = 'c0a20d6a2c64'
down_revision = 'b3bb6d961e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', postgresql.JSON(astext_type=Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
