"""empty message

Revision ID: c11c95c21bbe
Revises: b36883bf1be2
Create Date: 2025-04-15 13:55:04.985363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11c95c21bbe'
down_revision = 'b36883bf1be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_grid_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('field_grid_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('field_grid_y')
        batch_op.drop_column('field_grid_x')

    # ### end Alembic commands ###
