"""Rename direction to orientation

Revision ID: ca51d3b2338e
Revises: 81d4c36e5215
Create Date: 2025-04-18 12:09:30.881286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca51d3b2338e'
down_revision = '81d4c36e5215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.String(length=10), nullable=True))
        batch_op.drop_column('direction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###
