"""empty message

Revision ID: e6e3e0973908
Revises: 147c1062dfb8
Create Date: 2025-04-25 09:05:24.031175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e3e0973908'
down_revision = '147c1062dfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
